name: feech
description: "Flutter Experience Emma Can Help"
version: 0.0.12
homepage: "https://www.emmacanhelp.com"

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  asn1lib: '>=1.5.2 <2.0.0' # https://pub.dev/packages/asn1lib
  async: '>=2.11.0 <3.0.0' # https://pub.dev/packages/async
  crypto: '>=3.0.3 <4.0.0' # https://pub.dev/packages/crypto
  flutter_cache_manager: '>=3.3.1 <4.0.0' # https://pub.dev/packages/flutter_cache_manager
  flutter_svg: '>=2.0.7 <3.0.0' # https://pub.dev/packages/flutter_svg
  geocoding: '>=3.0.0 <4.0.0' # https://pub.dev/packages/geocoding
  google_maps_flutter: '>=2.6.0 <3.0.0' # https://pub.dev/packages/google_maps_flutter
  http: '>=0.13.6 <2.0.0' # https://pub.dev/packages/http
  image: '>=4.1.7 <5.0.0' # https://pub.dev/packages/image
  intl: '>=0.18.1 <1.0.0' # https://pub.dev/packages/intl
  quiver: '>=3.2.1 <4.0.0' # https://pub.dev/packages/quiver

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=3.0.2 <4.0.0'

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/auth0_landing/
    - assets/html/
    - assets/images/
    - assets/pems/
    - assets/data/toilets_filtered.json
    - assets/data/water_fountains.json
    - assets/data/two-min-passenger_zones.json
  shaders:
    - assets/shaders/art_fractal.frag
    - assets/shaders/image_blur.frag
    - assets/shaders/lsd_effect.frag
    - assets/shaders/mandelbrot_distance.frag
    - assets/shaders/scorpion_tail.frag
    - assets/shaders/the_clouds.frag
    - assets/shaders/water_ripple.frag
    - assets/shaders/pixelation.frag
    - assets/shaders/wave.frag
    - assets/shaders/wave2.frag
    - assets/shaders/mandelbulb.frag