name: feech
description: "Flutter Experience Emma Can Help"
version: 0.0.17
homepage: "https://www.emmacanhelp.com"

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  asn1lib: '>=1.5.2 <2.0.0' # https://pub.dev/packages/asn1lib
  async: '>=2.11.0 <3.0.0' # https://pub.dev/packages/async
  cloud_firestore: ">=4.17.0 <5.0.0" # https://pub.dev/packages/cloud_firestore
  crypto: '>=3.0.3 <4.0.0' # https://pub.dev/packages/crypto
  flutter_cache_manager: '>=3.3.1 <4.0.0' # https://pub.dev/packages/flutter_cache_manager
  flutter_svg: '>=2.0.7 <3.0.0' # https://pub.dev/packages/flutter_svg
  freezed_annotation: '>=2.4.1 <3.0.0' # https://pub.dev/packages/freezed_annotation
  geocoding: '>=3.0.0 <4.0.0' # https://pub.dev/packages/geocoding
  google_maps_flutter: '>=2.2.8 <3.0.0' # https://pub.dev/packages/google_maps_flutter
  http: '>=0.13.6 <2.0.0' # https://pub.dev/packages/http
  image: '>=4.1.7 <5.0.0' # https://pub.dev/packages/image
  intl: '>=0.18.1 <1.0.0' # https://pub.dev/packages/intl
  json_annotation: '>=4.8.1 <5.0.0' # https://pub.dev/packages/json_annotation
  quiver: '>=3.2.1 <4.0.0' # https://pub.dev/packages/quiver
  riverpod_annotation: '>=2.3.5 <3.0.0' # https://pub.dev/packages/riverpod_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=2.4.9 <3.0.0' # https://pub.dev/packages/build_runner
  flutter_lints: '>=3.0.2 <4.0.0' # https://pub.dev/packages/flutter_lints
  freezed: '>=2.5.2 <3.0.0' # https://pub.dev/packages/freezed
  json_serializable: '>=6.7.1 <7.0.0' # https://pub.dev/packages/json_serializable
  riverpod_generator: '>=2.4.0 <3.0.0' # https://pub.dev/packages/riverpod_generator

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/auth0_landing/
    - assets/html/
    - assets/images/
    - assets/pems/
    - assets/data/toilets_filtered.json
    - assets/data/water_fountains.json
    - assets/data/two-min-passenger_zones.json
  shaders:
    - assets/shaders/art_fractal.frag
    - assets/shaders/image_blur.frag
    - assets/shaders/lsd_effect.frag
    - assets/shaders/mandelbrot_distance.frag
    - assets/shaders/scorpion_tail.frag
    - assets/shaders/the_clouds.frag
    - assets/shaders/water_ripple.frag
    - assets/shaders/pixelation.frag
    - assets/shaders/wave.frag
    - assets/shaders/wave2.frag
    - assets/shaders/mandelbulb.frag