name: feech
version: 0.0.79
description: "Flutter Experience Emma Can Help"
homepage: "https://github.com/shanyuliang/feech"
repository: "https://github.com/shanyuliang/feech"
issue_tracker: "https://github.com/shanyuliang/feech/issues"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  asn1lib: '>=1.5.2 <2.0.0' # https://pub.dev/packages/asn1lib
  async: '>=2.11.0 <3.0.0' # https://pub.dev/packages/async
  camera: '>=0.10.5+9 <1.0.0' # https://pub.dev/packages/camera
  collection: '>=1.18.0 <2.0.0' # https://pub.dev/packages/collection
  cloud_firestore: ">=5.1.0 <6.0.0" # https://pub.dev/packages/cloud_firestore
  crypto: '>=3.0.3 <4.0.0' # https://pub.dev/packages/crypto
  firebase_crashlytics: '>=4.0.3 <5.0.0' # https://pub.dev/packages/firebase_crashlytics
  flutter_cache_manager: '>=3.3.1 <4.0.0' # https://pub.dev/packages/flutter_cache_manager
  flutter_riverpod: '>=2.5.1 <3.0.0' # https://pub.dev/packages/flutter_riverpod
  flutter_svg: '>=2.0.7 <3.0.0' # https://pub.dev/packages/flutter_svg
  flutter_tts: '>=4.0.2 <5.0.0' # https://pub.dev/packages/flutter_tts
  freezed_annotation: '>=2.4.3 <3.0.0' # https://pub.dev/packages/freezed_annotation
  geocoding: '>=3.0.0 <4.0.0' # https://pub.dev/packages/geocoding
  geolocator: '>=11.0.0 <13.0.0' # https://pub.dev/packages/geolocator
  go_router: '>=14.2.0 <15.0.0' # https://pub.dev/packages/go_router
  google_maps_flutter: '>=2.7.0 <3.0.0' # https://pub.dev/packages/google_maps_flutter
  http: '>=0.13.6 <2.0.0' # https://pub.dev/packages/http
  image: '>=4.2.0 <5.0.0' # https://pub.dev/packages/image
  intl: '>=0.18.1 <1.0.0' # https://pub.dev/packages/intl
  json_annotation: '>=4.9.0 <5.0.0' # https://pub.dev/packages/json_annotation
  logging: '>=1.2.0 <2.0.0' # https://pub.dev/packages/logging
  newrelic_mobile: '>=1.0.9 <2.0.0' # https://pub.dev/packages/newrelic_mobile
  permission_handler: '>=11.3.1 <12.0.0' # https://pub.dev/packages/permission_handler
  quiver: '>=3.2.1 <4.0.0' # https://pub.dev/packages/quiver
  riverpod_annotation: '>=2.3.5 <3.0.0' # https://pub.dev/packages/riverpod_annotation
  shared_preferences: '>=2.2.3 <3.0.0' # https://pub.dev/packages/shared_preferences
  speech_to_text: '>=6.6.0 <7.0.0' # https://pub.dev/packages/speech_to_text
  sqflite: '>=2.3.3 <3.0.0' # https://pub.dev/packages/sqflite
  ulid4d: '>=2.0.0 <3.0.0' # https://pub.dev/packages/ulid4d
  webview_flutter: '>=4.8.0 <5.0.0' # https://pub.dev/packages/webview_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=2.4.11 <3.0.0' # https://pub.dev/packages/build_runner
  flutter_lints: '>=4.0.0 <5.0.0' # https://pub.dev/packages/flutter_lints
  freezed: '>=2.5.2 <3.0.0' # https://pub.dev/packages/freezed
  json_serializable: '>=6.8.0 <7.0.0' # https://pub.dev/packages/json_serializable
  riverpod_analyzer_utils: '>=0.5.1 <1.0.0' # https://pub.dev/packages/riverpod_analyzer_utils
  riverpod_generator: '>=2.4.0 <3.0.0' # https://pub.dev/packages/riverpod_generator
  riverpod_lint: '>=2.3.10 <3.0.0' # https://pub.dev/packages/riverpod_lint

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/auth0_landing/
    - assets/html/
    - assets/images/
    - assets/pems/
    - assets/data/toilets_filtered.json
    - assets/data/water_fountains.json
    - assets/data/two-min-passenger_zones.json
  shaders:
    - assets/shaders/art_fractal.frag
    - assets/shaders/image_blur.frag
    - assets/shaders/lsd_effect.frag
    - assets/shaders/mandelbrot_distance.frag
    - assets/shaders/scorpion_tail.frag
    - assets/shaders/the_clouds.frag
    - assets/shaders/water_ripple.frag
    - assets/shaders/wave.frag
    - assets/shaders/wave2.frag
    - assets/shaders/mandelbulb.frag