name: feech
version: 0.1.58
description: "Flutter Experience Emma Can Help"
homepage: "https://github.com/shanyuliang/feech"
repository: "https://github.com/shanyuliang/feech"
issue_tracker: "https://github.com/shanyuliang/feech/issues"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.35.4"

dependencies:
  flutter:
    sdk: flutter
  asn1lib: '>=1.6.5 <2.0.0' # https://pub.dev/packages/asn1lib
  async: '>=2.13.0 <3.0.0' # https://pub.dev/packages/async
  camera: '>=0.11.2 <1.0.0' # https://pub.dev/packages/camera
  cloud_firestore: ">=6.0.2 <7.0.0" # https://pub.dev/packages/cloud_firestore
  collection: '>=1.19.1 <2.0.0' # https://pub.dev/packages/collection
  crypto: '>=3.0.6 <4.0.0' # https://pub.dev/packages/crypto
  device_info_plus: '>=12.1.0 <13.0.0' # https://pub.dev/packages/device_info_plus
  firebase_crashlytics: '>=5.0.2 <6.0.0' # https://pub.dev/packages/firebase_crashlytics
  flutter_cache_manager: '>=3.4.1 <4.0.0' # https://pub.dev/packages/flutter_cache_manager
  flutter_riverpod: '>=3.0.0 <4.0.0' # https://pub.dev/packages/flutter_riverpod
  flutter_svg: '>=2.2.1 <3.0.0' # https://pub.dev/packages/flutter_svg
  flutter_tts: '>=4.2.3 <5.0.0' # https://pub.dev/packages/flutter_tts
  freezed_annotation: '>=3.1.0 <4.0.0' # https://pub.dev/packages/freezed_annotation
  geocoding: '>=4.0.0 <5.0.0' # https://pub.dev/packages/geocoding
  geolocator: '>=14.0.2 <15.0.0' # https://pub.dev/packages/geolocator
  go_router: '>=16.2.2 <17.0.0' # https://pub.dev/packages/go_router
  google_maps_flutter: '>=2.13.1 <3.0.0' # https://pub.dev/packages/google_maps_flutter
  http: '>=1.5.0 <2.0.0' # https://pub.dev/packages/http
  image: '>=4.5.4 <5.0.0' # https://pub.dev/packages/image
  intl: any # https://pub.dev/packages/intl
  json_annotation: '>=4.9.0 <5.0.0' # https://pub.dev/packages/json_annotation
  logging: '>=1.3.0 <2.0.0' # https://pub.dev/packages/logging
  mime: '>=2.0.0 <3.0.0' # https://pub.dev/packages/mime
  newrelic_mobile: '>=1.1.14 <2.0.0' # https://pub.dev/packages/newrelic_mobile
  package_info_plus: '>=8.3.1 <9.0.0' # https://pub.dev/packages/package_info_plus
  palette_generator: '>=0.3.3+7 <1.0.0' # https://pub.dev/packages/palette_generator
  permission_handler: '>=12.0.1 <13.0.0' # https://pub.dev/packages/permission_handler
  pointer_interceptor: '>=0.10.1+2 <1.0.0' # https://pub.dev/packages/pointer_interceptor
  quiver: '>=3.2.2 <4.0.0' # https://pub.dev/packages/quiver
  riverpod_annotation: '>=3.0.0 <4.0.0' # https://pub.dev/packages/riverpod_annotation
  shared_preferences: '>=2.5.3 <3.0.0' # https://pub.dev/packages/shared_preferences
  signals_flutter: '>=6.0.2 <7.0.0' # https://pub.dev/packages/signals_flutter
  speech_to_text: '>=7.3.0 <8.0.0' # https://pub.dev/packages/speech_to_text
  sqflite: '>=2.4.2 <3.0.0' # https://pub.dev/packages/sqflite
  ulid4d: '>=2.0.0 <3.0.0' # https://pub.dev/packages/ulid4d
  version: '>=3.0.2 <4.0.0' # https://pub.dev/packages/version
  web: '>=1.1.1 <2.0.0' # https://pub.dev/packages/web
  webview_flutter: '>=4.13.0 <5.0.0' # https://pub.dev/packages/webview_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=2.7.1 <3.0.0' # https://pub.dev/packages/build_runner
  flutter_lints: '>=6.0.0 <7.0.0' # https://pub.dev/packages/flutter_lints
  freezed: '>=3.2.3 <4.0.0' # https://pub.dev/packages/freezed
  json_serializable: '>=6.11.1 <7.0.0' # https://pub.dev/packages/json_serializable
  riverpod_analyzer_utils: '>=1.0.0-dev.6 <2.0.0' # https://pub.dev/packages/riverpod_analyzer_utils
  riverpod_generator: '>=3.0.0 <4.0.0' # https://pub.dev/packages/riverpod_generator
  riverpod_lint: '>=3.0.0 <4.0.0' # https://pub.dev/packages/riverpod_lint

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/auth0_landing/
    - assets/html/
    - assets/images/
    - assets/pems/
    - assets/data/toilets_filtered.json
    - assets/data/water_fountains.json
    - assets/data/two-min-passenger_zones.json
  shaders:
    - assets/shaders/art_fractal.frag
    - assets/shaders/image_blur.frag
    - assets/shaders/lsd_effect.frag
    - assets/shaders/mandelbrot_distance.frag
    - assets/shaders/scorpion_tail.frag
    - assets/shaders/the_clouds.frag
    - assets/shaders/water_ripple.frag
    - assets/shaders/wave.frag
    - assets/shaders/wave2.frag
    - assets/shaders/mandelbulb.frag